medical_study_abroad_keywords = [
            "Medical study abroad",
            "Study medicine abroad",
            "Medical studies overseas",
            "International medical studies",
            "Global medical education",
            "MBBS study abroad",
            "MD study abroad",
            "MS study abroad",
            "MSc study abroad",
            "PhD study abroad",
            "Medical research abroad",
            "Clinical trials abroad",
            "Medical internship abroad",
            "Medical study in USA",
            "Medical study in UK",
            "Medical study in Canada",
            "Medical study in Australia",
            "Medical study in Germany",
            "Medical study in New Zealand",
            "Medical study in Singapore",
            "Medical study in Ireland",
            "Medical study in France",
            "Medical study in Europe",
            "Medical study in Asia",
            "Medical study in Africa",
            "Medical study in South America",
            "Medical study in North America",
            "Medical study in Australia and Oceania",
            "Medical study abroad scholarships",
            "Full scholarship for medical study abroad",
            "Partial scholarship for medical study abroad",
            "Government scholarship for medical study abroad",
            "Private scholarship for medical study abroad",
            "Medical study abroad visa requirements",
            "Student visa for medical study abroad",
            "Work visa for medical study abroad",
            "Visa application process for medical study abroad",
            "Visa interview questions for medical study abroad",
            "Medical study abroad career opportunities",
            "Job opportunities after medical study abroad",
            "Career prospects after medical study abroad",
            "Salary expectations after medical study abroad",
            "Professional development after medical study abroad",
            "Medical study abroad consultants",
            "Medical study abroad agencies",
            "Medical study abroad programs",
            "Medical study abroad courses",
            "Medical study abroad universities",
            "Medical study abroad colleges",
            "Medical study abroad institutions",
            "Medical study abroad schools",
            "Study medicine in abroad",
            "Medical education abroad",
            "International medical education",
            "Global health education",
            "Medical research opportunities abroad",
            "Clinical trials abroad for students",
            "Medical internship abroad for students",
            "Medical study abroad for Indian students",
            "Medical study abroad for international students",
            "Medical study abroad without NEET",
            "Medical study abroad without IELTS",
            "Medical study abroad without TOEFL",
            "Medical study abroad with scholarship",
            "Medical study abroad with low fees",
            "Medical study abroad with high salary",
            "Medical study abroad with job guarantee",
            "Medical study abroad with internship",
            "Medical study abroad with research opportunities",
            "study abroad consultants for MBA in USA from India",
            "overseas education consultants for engineering in UK from India",
            "best study abroad destinations for Indian students",
            "study abroad scholarships for Indian students",
            "top study abroad consultants in India for studying in Canada",
            "study abroad consultants for MBA in USA from India",
            "overseas education consultants for engineering in UK from India",
            "best study abroad destinations for Indian students",
            "study abroad scholarships for Indian students",
            "top study abroad consultants in India for studying in Canada",
            "study abroad consultants in India",
            "overseas education consultants in India",
            "study abroad in USA from India",
            "study in UK from India",
            "study in Canada from India",
            "study abroad consultants in Mumbai",
            "study abroad consultants in Delhi",
            "study abroad consultants in Bangalore",
            "study abroad consultants in Chennai",
            "study abroad consultants in Hyderabad",
            "IELTS preparation",
            "TOEFL preparation",
            "GRE preparation",
            "GMAT preparation",
            "SAT preparation",
            "scholarship for international students",
            "study abroad scholarships",
            "education loan for abroad studies",
            "abroad study visa",
            "overseas education consultants",
            "MBA abroad",
            "engineering studies abroad",
            "medical studies abroad",
            "business studies abroad",
            "arts and design abroad",
            "science and technology abroad",
            "humanities abroad",
            "law studies abroad",
            "master's degree abroad",
            "bachelor's degree abroad",
            "Medical study in USA",
            "Medical study in UK",
            "Medical study in Canada",
            "Medical study in Australia",
            "Medical study in Germany",
            "Medical study in New Zealand",
            "Medical study in Singapore",
            "Medical study in Ireland",
            "Medical study in France",
            "Medical study in Europe",
            # General Medical Consultancy Keywords
            "Medical consultancy services",
            "Healthcare consulting firms",
            "Medical practice consulting",
            "Clinical consultancy services",
            "Healthcare management consulting",

            # Specialized Medical Consultancy Keywords
            "Telemedicine consulting services",
            "Digital health consulting",
            "Medical tourism consulting",
            "Healthcare IT consulting",
            "Clinical research consulting",

            # Medical Consultancy Services Keywords
            "Medical billing and coding consulting",
            "Practice management consulting",
            "Clinical operations consulting",
            "Medical staffing consulting",
            "Healthcare marketing consulting",

            # Location-Based Medical Consultancy Keywords
            "Medical consultancy services in India",
            "Healthcare consulting firms in India",
            "Medical practice consulting in India",
            "Clinical consultancy services in India",
            "Healthcare management consulting in India"# General Medical Consultancy Keywords
            "Medical consultancy services",
            "Healthcare consulting firms",
            "Medical practice consulting",
            "Clinical consultancy services",
            "Healthcare management consulting",

            # Specialized Medical Consultancy Keywords
            "Telemedicine consulting services",
            "Digital health consulting",
            "Medical tourism consulting",
            "Healthcare IT consulting",
            "Clinical research consulting",

            # Medical Consultancy Services Keywords
            "Medical billing and coding consulting",
            "Practice management consulting",
            "Clinical operations consulting",
            "Medical staffing consulting",
            "Healthcare marketing consulting",

            # Location-Based Medical Consultancy Keywords
            "Medical consultancy services in India",
            "Healthcare consulting firms in India",
            "Medical practice consulting in India",
            "Clinical consultancy services in India",
            "Healthcare management consulting in India",
             # More Keywords
            "Medical study abroad consultants",
            "Medical study abroad agencies",
            "Medical study abroad programs",
            "Medical study abroad courses",
            "Medical study abroad universities",
            "Medical study abroad colleges",
            "Medical study abroad institutions",
            "Medical study abroad schools",
            "Study medicine in abroad",
            "Medical education abroad",
            "International medical education",
            "Global health education",
            "Medical research opportunities abroad",
            "Clinical trials abroad for students",
            "Medical internship abroad for students",
            "Medical study abroad for Indian students",
            "Medical study abroad for international students",
            "Medical study abroad without NEET",
            "Medical study abroad without IELTS",
            "Medical study abroad without TOEFL",
            "Medical study abroad with scholarship",
            "Medical study abroad with low fees",
            "Medical study abroad with high salary",
            "Medical study abroad with job guarantee",
            "Medical study abroad with internship",
            "Medical study abroad with research opportunities",
            "Best medical universities abroad",
            "Top medical colleges abroad",
            "Medical study abroad admission process",
            "Medical study abroad eligibility criteria",
            "Medical study abroad fees structure",
            "Medical study abroad scholarships for Indian students",
            "Medical study abroad scholarships for international students",
            "Medical study abroad loans for Indian students",
            "Medical study abroad loans for international students",
            "Medical study abroad accommodation options",
            "Medical study abroad food options",
            "Medical study abroad transportation options",
            "Medical study abroad lifestyle",
            "Medical study abroad culture",
            "Medical study abroad language",
            "Medical study abroad safety",
            "Medical study abroad security",
            "Medical study abroad reviews",
            "Medical study abroad testimonials",
            "Medical study abroad ratings",
            "Medical study abroad rankings",
            "Medical study abroad forums",
            "Medical study abroad blogs",
            "Medical study abroad news",
            "Medical study abroad updates",
            "Medical study abroad alerts",
            "Medical study abroad notifications",
            "Medical study abroad reminders",
            "Medical study abroad deadlines",
            "Medical study abroad applications",
            "Medical study abroad forms",
            "Medical study abroad documents",
            "Medical study abroad certificates",
            "Medical study abroad transcripts",
            "Medical study abroad diplomas",
            "Medical study abroad degrees",
            "Medical study abroad certifications",
            "Medical study abroad licenses",
            "Medical study abroad permits",
            "Medical study abroad visas",
            "Medical study abroad passports",
            "Medical study abroad travel",
            "Medical study abroad tourism",
            "Medical study abroad hospitality",
            "Medical study abroad services",
             # General Keywords
        "Medical study abroad",
        "Study medicine abroad",
        "Medical studies overseas",
        "International medical studies",
        "Global medical education",
        # ... (970 more keywords)
        "Medical study abroad consultants",
        "Medical study abroad agencies",
        "Medical study abroad programs",
        "Medical study abroad courses",
        "Medical study abroad universities",
        "Medical study abroad colleges",
        "Medical study abroad institutions",
        "Medical study abroad schools",
        "Study medicine in abroad",
        "Medical education abroad",
        "International medical education",
        "Global health education",
        "Medical research opportunities abroad",
        "Clinical trials abroad for students",
        "Medical internship abroad for students",
        "Medical study abroad for Indian students",
        "Medical study abroad for international students",
        # ... (950 more keywords)
        "Best medical universities abroad",
        "Top medical colleges abroad",
        "Medical study abroad admission process",
        "Medical study abroad eligibility criteria",
        "Medical study abroad fees structure",
        "Medical study abroad scholarships for Indian students",
        "Medical study abroad scholarships for international students",
        # ... (900 more keywords)
        "Medical study abroad loans for Indian students",
        "Medical study abroad loans for international students",
        "Medical study abroad accommodation options",
        "Medical study abroad food options",
        "Medical study abroad transportation options",
        "Medical study abroad lifestyle",
        "Medical study abroad culture",
        "Medical study abroad language",
        "Medical study abroad safety",
        "Medical study abroad security",
        # ... (850 more keywords)
        "Medical study abroad reviews",
        "Medical study abroad testimonials",
        "Medical study abroad ratings",
        "Medical study abroad rankings",
        "Medical study abroad forums",
        "Medical study abroad blogs",
        "Medical study abroad news",
        "Medical study abroad updates",
        "Medical study abroad alerts",
        # ... (800 more keywords)
        "Medical study abroad notifications",
        "Medical study abroad reminders",
        "Medical study abroad deadlines",
        "Medical study abroad applications",
        "Medical study abroad forms",
        "Medical study abroad documents",
        "Medical study abroad certificates",
        "Medical study abroad transcripts",
        "Medical study abroad diplomas",
        # ... (750 more keywords)
        "Medical study abroad degrees",
        "Medical study abroad certifications",
        "Medical study abroad licenses",
        "Medical study abroad permits",
        "Medical study abroad visas",
        "Medical study abroad passports",
        "Medical study abroad travel",
        "Medical study abroad tourism",
        "Medical study abroad hospitality",
        "Medical study abroad services",
        # ... (700 more keywords)
        "Medical study abroad consultants",
        "Medical study abroad agencies",
        "Medical study abroad programs",
        "Medical study abroad courses",
        "Medical study abroad universities",
        "Medical study abroad colleges",
        "Medical study abroad institutions",
        "Medical study abroad schools",
        # ... (650 more keywords)
        "Study medicine in abroad",
        "Medical education abroad",
        "International medical education",
        "Global health education",
        "Medical research opportunities abroad",
        "Clinical trials abroad for students",
        "Medical internship abroad for students",
        "Medical study abroad for Indian students",
        "Medical study abroad for international students",
        # ... (600 more keywords)
        "Best medical universities abroad",
        "Top medical colleges abroad",
        "Medical study abroad admission process",
        "Medical study abroad eligibility criteria",
        "Medical study abroad fees structure",
        "Medical study abroad scholarships for Indian students",
        "Medical study abroad scholarships for international students",
        # ... (550 more keywords)
        "Medical study abroad loans for Indian students",
        "Medical study abroad loans for international students",
        "Medical study abroad accommodation options",
        "Medical study abroad food options",
        "Medical study abroad transportation options",
        "Medical study abroad lifestyle",
        "Medical study abroad culture",
        "Medical study abroad language",
        # ... (500 more keywords)
        "Medical study abroad safety",
        "Medical study abroad security",
        "Medical study abroad reviews",
        "Medical study abroad testimonials",
        "Medical study abroad ratings",
        "Medical study abroad rankings",
        "Medical study abroad forums",
        "Medical study abroad blogs",
        # ... (450 more keywords)
        "Medical study abroad news",
        "Medical study abroad updates",
        "Medical study abroad alerts",
        "Medical study abroad notifications",
        "Medical study abroad reminders",
        "Medical study abroad deadlines",
        "Medical study abroad applications",
        "Medical study abroad forms",
        # ... (400 more keywords)
        "Medical study abroad documents",
        "Medical study abroad certificates",
        "Medical study abroad transcripts",
        "Medical study abroad diplomas",
        "Medical study abroad degrees",

        ]medical_study_abroad_keywords = [
            "Medical study abroad",
            "Study medicine abroad",
            "Medical studies overseas",
            "International medical studies",
            "Global medical education",
            "MBBS study abroad",
            "MD study abroad",
            "MS study abroad",
            "MSc study abroad",
            "PhD study abroad",
            "Medical research abroad",
            "Clinical trials abroad",
            "Medical internship abroad",
            "Medical study in USA",
            "Medical study in UK",
            "Medical study in Canada",
            "Medical study in Australia",
            "Medical study in Germany",
            "Medical study in New Zealand",
            "Medical study in Singapore",
            "Medical study in Ireland",
            "Medical study in France",
            "Medical study in Europe",
            "Medical study in Asia",
            "Medical study in Africa",
            "Medical study in South America",
            "Medical study in North America",
            "Medical study in Australia and Oceania",
            "Medical study abroad scholarships",
            "Full scholarship for medical study abroad",
            "Partial scholarship for medical study abroad",
            "Government scholarship for medical study abroad",
            "Private scholarship for medical study abroad",
            "Medical study abroad visa requirements",
            "Student visa for medical study abroad",
            "Work visa for medical study abroad",
            "Visa application process for medical study abroad",
            "Visa interview questions for medical study abroad",
            "Medical study abroad career opportunities",
            "Job opportunities after medical study abroad",
            "Career prospects after medical study abroad",
            "Salary expectations after medical study abroad",
            "Professional development after medical study abroad",
            "Medical study abroad consultants",
            "Medical study abroad agencies",
            "Medical study abroad programs",
            "Medical study abroad courses",
            "Medical study abroad universities",
            "Medical study abroad colleges",
            "Medical study abroad institutions",
            "Medical study abroad schools",
            "Study medicine in abroad",
            "Medical education abroad",
            "International medical education",
            "Global health education",
            "Medical research opportunities abroad",
            "Clinical trials abroad for students",
            "Medical internship abroad for students",
            "Medical study abroad for Indian students",
            "Medical study abroad for international students",
            "Medical study abroad without NEET",
            "Medical study abroad without IELTS",
            "Medical study abroad without TOEFL",
            "Medical study abroad with scholarship",
            "Medical study abroad with low fees",
            "Medical study abroad with high salary",
            "Medical study abroad with job guarantee",
            "Medical study abroad with internship",
            "Medical study abroad with research opportunities",
            "study abroad consultants for MBA in USA from India",
            "overseas education consultants for engineering in UK from India",
            "best study abroad destinations for Indian students",
            "study abroad scholarships for Indian students",
            "top study abroad consultants in India for studying in Canada",
            "study abroad consultants for MBA in USA from India",
            "overseas education consultants for engineering in UK from India",
            "best study abroad destinations for Indian students",
            "study abroad scholarships for Indian students",
            "top study abroad consultants in India for studying in Canada",
            "study abroad consultants in India",
            "overseas education consultants in India",
            "study abroad in USA from India",
            "study in UK from India",
            "study in Canada from India",
            "study abroad consultants in Mumbai",
            "study abroad consultants in Delhi",
            "study abroad consultants in Bangalore",
            "study abroad consultants in Chennai",
            "study abroad consultants in Hyderabad",
            "IELTS preparation",
            "TOEFL preparation",
            "GRE preparation",
            "GMAT preparation",
            "SAT preparation",
            "scholarship for international students",
            "study abroad scholarships",
            "education loan for abroad studies",
            "abroad study visa",
            "overseas education consultants",
            "MBA abroad",
            "engineering studies abroad",
            "medical studies abroad",
            "business studies abroad",
            "arts and design abroad",
            "science and technology abroad",
            "humanities abroad",
            "law studies abroad",
            "master's degree abroad",
            "bachelor's degree abroad",
            "Medical study in USA",
            "Medical study in UK",
            "Medical study in Canada",
            "Medical study in Australia",
            "Medical study in Germany",
            "Medical study in New Zealand",
            "Medical study in Singapore",
            "Medical study in Ireland",
            "Medical study in France",
            "Medical study in Europe",
            # General Medical Consultancy Keywords
            "Medical consultancy services",
            "Healthcare consulting firms",
            "Medical practice consulting",
            "Clinical consultancy services",
            "Healthcare management consulting",

            # Specialized Medical Consultancy Keywords
            "Telemedicine consulting services",
            "Digital health consulting",
            "Medical tourism consulting",
            "Healthcare IT consulting",
            "Clinical research consulting",

            # Medical Consultancy Services Keywords
            "Medical billing and coding consulting",
            "Practice management consulting",
            "Clinical operations consulting",
            "Medical staffing consulting",
            "Healthcare marketing consulting",

            # Location-Based Medical Consultancy Keywords
            "Medical consultancy services in India",
            "Healthcare consulting firms in India",
            "Medical practice consulting in India",
            "Clinical consultancy services in India",
            "Healthcare management consulting in India"# General Medical Consultancy Keywords
            "Medical consultancy services",
            "Healthcare consulting firms",
            "Medical practice consulting",
            "Clinical consultancy services",
            "Healthcare management consulting",

            # Specialized Medical Consultancy Keywords
            "Telemedicine consulting services",
            "Digital health consulting",
            "Medical tourism consulting",
            "Healthcare IT consulting",
            "Clinical research consulting",

            # Medical Consultancy Services Keywords
            "Medical billing and coding consulting",
            "Practice management consulting",
            "Clinical operations consulting",
            "Medical staffing consulting",
            "Healthcare marketing consulting",

            # Location-Based Medical Consultancy Keywords
            "Medical consultancy services in India",
            "Healthcare consulting firms in India",
            "Medical practice consulting in India",
            "Clinical consultancy services in India",
            "Healthcare management consulting in India",
             # More Keywords
            "Medical study abroad consultants",
            "Medical study abroad agencies",
            "Medical study abroad programs",
            "Medical study abroad courses",
            "Medical study abroad universities",
            "Medical study abroad colleges",
            "Medical study abroad institutions",
            "Medical study abroad schools",
            "Study medicine in abroad",
            "Medical education abroad",
            "International medical education",
            "Global health education",
            "Medical research opportunities abroad",
            "Clinical trials abroad for students",
            "Medical internship abroad for students",
            "Medical study abroad for Indian students",
            "Medical study abroad for international students",
            "Medical study abroad without NEET",
            "Medical study abroad without IELTS",
            "Medical study abroad without TOEFL",
            "Medical study abroad with scholarship",
            "Medical study abroad with low fees",
            "Medical study abroad with high salary",
            "Medical study abroad with job guarantee",
            "Medical study abroad with internship",
            "Medical study abroad with research opportunities",
            "Best medical universities abroad",
            "Top medical colleges abroad",
            "Medical study abroad admission process",
            "Medical study abroad eligibility criteria",
            "Medical study abroad fees structure",
            "Medical study abroad scholarships for Indian students",
            "Medical study abroad scholarships for international students",
            "Medical study abroad loans for Indian students",
            "Medical study abroad loans for international students",
            "Medical study abroad accommodation options",
            "Medical study abroad food options",
            "Medical study abroad transportation options",
            "Medical study abroad lifestyle",
            "Medical study abroad culture",
            "Medical study abroad language",
            "Medical study abroad safety",
            "Medical study abroad security",
            "Medical study abroad reviews",
            "Medical study abroad testimonials",
            "Medical study abroad ratings",
            "Medical study abroad rankings",
            "Medical study abroad forums",
            "Medical study abroad blogs",
            "Medical study abroad news",
            "Medical study abroad updates",
            "Medical study abroad alerts",
            "Medical study abroad notifications",
            "Medical study abroad reminders",
            "Medical study abroad deadlines",
            "Medical study abroad applications",
            "Medical study abroad forms",
            "Medical study abroad documents",
            "Medical study abroad certificates",
            "Medical study abroad transcripts",
            "Medical study abroad diplomas",
            "Medical study abroad degrees",
            "Medical study abroad certifications",
            "Medical study abroad licenses",
            "Medical study abroad permits",
            "Medical study abroad visas",
            "Medical study abroad passports",
            "Medical study abroad travel",
            "Medical study abroad tourism",
            "Medical study abroad hospitality",
            "Medical study abroad services",
             # General Keywords
        "Medical study abroad",
        "Study medicine abroad",
        "Medical studies overseas",
        "International medical studies",
        "Global medical education",
        # ... (970 more keywords)
        "Medical study abroad consultants",
        "Medical study abroad agencies",
        "Medical study abroad programs",
        "Medical study abroad courses",
        "Medical study abroad universities",
        "Medical study abroad colleges",
        "Medical study abroad institutions",
        "Medical study abroad schools",
        "Study medicine in abroad",
        "Medical education abroad",
        "International medical education",
        "Global health education",
        "Medical research opportunities abroad",
        "Clinical trials abroad for students",
        "Medical internship abroad for students",
        "Medical study abroad for Indian students",
        "Medical study abroad for international students",
        # ... (950 more keywords)
        "Best medical universities abroad",
        "Top medical colleges abroad",
        "Medical study abroad admission process",
        "Medical study abroad eligibility criteria",
        "Medical study abroad fees structure",
        "Medical study abroad scholarships for Indian students",
        "Medical study abroad scholarships for international students",
        # ... (900 more keywords)
        "Medical study abroad loans for Indian students",
        "Medical study abroad loans for international students",
        "Medical study abroad accommodation options",
        "Medical study abroad food options",
        "Medical study abroad transportation options",
        "Medical study abroad lifestyle",
        "Medical study abroad culture",
        "Medical study abroad language",
        "Medical study abroad safety",
        "Medical study abroad security",
        # ... (850 more keywords)
        "Medical study abroad reviews",
        "Medical study abroad testimonials",
        "Medical study abroad ratings",
        "Medical study abroad rankings",
        "Medical study abroad forums",
        "Medical study abroad blogs",
        "Medical study abroad news",
        "Medical study abroad updates",
        "Medical study abroad alerts",
        # ... (800 more keywords)
        "Medical study abroad notifications",
        "Medical study abroad reminders",
        "Medical study abroad deadlines",
        "Medical study abroad applications",
        "Medical study abroad forms",
        "Medical study abroad documents",
        "Medical study abroad certificates",
        "Medical study abroad transcripts",
        "Medical study abroad diplomas",
        # ... (750 more keywords)
        "Medical study abroad degrees",
        "Medical study abroad certifications",
        "Medical study abroad licenses",
        "Medical study abroad permits",
        "Medical study abroad visas",
        "Medical study abroad passports",
        "Medical study abroad travel",
        "Medical study abroad tourism",
        "Medical study abroad hospitality",
        "Medical study abroad services",
        # ... (700 more keywords)
        "Medical study abroad consultants",
        "Medical study abroad agencies",
        "Medical study abroad programs",
        "Medical study abroad courses",
        "Medical study abroad universities",
        "Medical study abroad colleges",
        "Medical study abroad institutions",
        "Medical study abroad schools",
        # ... (650 more keywords)
        "Study medicine in abroad",
        "Medical education abroad",
        "International medical education",
        "Global health education",
        "Medical research opportunities abroad",
        "Clinical trials abroad for students",
        "Medical internship abroad for students",
        "Medical study abroad for Indian students",
        "Medical study abroad for international students",
        # ... (600 more keywords)
        "Best medical universities abroad",
        "Top medical colleges abroad",
        "Medical study abroad admission process",
        "Medical study abroad eligibility criteria",
        "Medical study abroad fees structure",
        "Medical study abroad scholarships for Indian students",
        "Medical study abroad scholarships for international students",
        # ... (550 more keywords)
        "Medical study abroad loans for Indian students",
        "Medical study abroad loans for international students",
        "Medical study abroad accommodation options",
        "Medical study abroad food options",
        "Medical study abroad transportation options",
        "Medical study abroad lifestyle",
        "Medical study abroad culture",
        "Medical study abroad language",
        # ... (500 more keywords)
        "Medical study abroad safety",
        "Medical study abroad security",
        "Medical study abroad reviews",
        "Medical study abroad testimonials",
        "Medical study abroad ratings",
        "Medical study abroad rankings",
        "Medical study abroad forums",
        "Medical study abroad blogs",
        # ... (450 more keywords)
        "Medical study abroad news",
        "Medical study abroad updates",
        "Medical study abroad alerts",
        "Medical study abroad notifications",
        "Medical study abroad reminders",
        "Medical study abroad deadlines",
        "Medical study abroad applications",
        "Medical study abroad forms",
        # ... (400 more keywords)
        "Medical study abroad documents",
        "Medical study abroad certificates",
        "Medical study abroad transcripts",
        "Medical study abroad diplomas",
        "Medical study abroad degrees",

        ]